### ISSUE TITLE
want: eslint等の整備

### ISSUE THREAD

**Issue by Sigumaa** [Growthers/Oshavery-Server#119]
## 概要
現在のeslintの設定はあくまでも仮でこのプロジェクトに合っていないので

## なぜIssueを作ったか
全部の行にエラー出ててつらいから

## 必要なこと
気合いと気力

**Comment by YukiYuigishi** [comment]
airbnbより緩めのルールを見つければだいぶ楽になると思います

**Comment by laminne** [comment]
Oshavery向けのルールを書いてマージされたのでクローズします
